### ISSUE TITLE
Step by Step

### ISSUE THREAD

**Issue by compulon** [selloween/docker-wordpress#10]
Step by Step:

1.- Clone docker-multi-wordpress
2.- Delete wordpress_02 and rename wordpress_01
3.- Rename it to .env
4.- Change the name of the container and the credentials of the database and wp
5.- Run docker-compose up -d in the nginx
6.- Run docker-compose up --build

Result: problem wp without design, imagine problem with css...
Note: I'm not touching the files: composer.json, Dockerfile, wp-config.php.

What am I doing wrong?

**Comment by selloween** [comment]
I can't reproduce your problem. The steps you describe are correct and work for me.

> Result: problem wp without design, imagine problem with css... <

Do you mean the frontend or the admin dashboard ? If you activated the custom theme - that's entirely barebone - just a index.php outputting "hello world" and a style.css without any styles.

**Comment by selloween** [comment]
Are you working locally? If so did you follow the step by adding a dummy domain to your hosts file ? If not you will get an 503 status code from the NGINX proxy.

**Comment by compulon** [comment]
I'm with digital ocean

**Comment by compulon** [comment]
in both cases...

**Comment by selloween** [comment]
This sounds like a problem with your server and not the docker setup. I would suggest checking if the containers are running with `docker ps`. Then check if the ports 80 and 443 are open on your host. Then check if the site is running using the IP address instead of the domain. Have you added a DNS entry pointing to host IP? Have you looked in the http response what status code comes back using the inspector tools of your browser ? There are too many factors - so i am afraid I can't really help you as this is not a bug or issue  in the docker setup files.

**Comment by compulon** [comment]
will be a limitation of digital ocean to force create a drop for each
wordpress ...

**Comment by selloween** [comment]
Afaik DigitalOcean Droplets are Docker containers - In general you can run Docker in Docker - but I would not suggest running multiple WP containers in a droplet/container - it would not surprise me if DigitalOcean prevents this.

**Comment by compulon** [comment]
I did something similar with a multi odoo docker without problems ... Let
me keep checking and trying to see what happens...
